name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop # or other branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          # If your app is in a subfolder of the repository,
          # specify that folder name here instead of 'dist'
          # publish_dir: your-app-folder/dist
          # cname: your-custom-domain.com # Optional, if you're using a custom domain
